/**
 * Copyright 2026 Salesforce, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { type ReactElement } from 'react';
import { useTranslation } from 'react-i18next';
import { cn } from '@/lib/utils';
import { Badge } from '@/components/ui/badge';
import { SparklesIcon } from '@/components/icons';
import { StarIcon } from '@/components/product-ratings/star-icon';

export interface AiReviewSummaryProps {
    /**
     * The title for the AI review summary section
     * @default "AI Review Summary"
     */
    title?: string;
    /**
     * Optional badge text to display next to the title (e.g., "Beta", "New")
     */
    badgeText?: string;
    /**
     * The summary description text generated by AI
     */
    description: string;
    /**
     * Average rating value (0-5)
     */
    rating: number;
    /**
     * Total number of reviews
     */
    reviewCount: number;
    /**
     * Additional CSS classes
     */
    className?: string;
}

/** Four-pointed sparkle in a square box with light blue background, per UX. */
function AiSparkleIcon({ className }: { className?: string }): ReactElement {
    return (
        <div
            className={cn('flex shrink-0 items-center justify-center rounded-lg w-8 h-8 sm:w-10 sm:h-10', className)}
            style={{ backgroundColor: 'var(--brand-blue-100)' }}
            aria-hidden="true">
            <SparklesIcon className="w-4 h-4 sm:w-5 sm:h-5" style={{ color: 'var(--brand-blue-600)' }} />
        </div>
    );
}

/**
 * AI Review Summary component displays an AI-generated summary of product reviews
 * with title, optional badge, description, and rating information.
 */
export function AiReviewSummary({
    title = 'AI Review Summary',
    badgeText,
    description,
    rating,
    reviewCount,
    className,
}: AiReviewSummaryProps): ReactElement {
    const { t } = useTranslation();
    const formattedRating = Number(rating.toFixed(1)).toString();

    return (
        <div
            className={cn('rounded-lg border border-border bg-background p-4', className)}
            data-testid="ai-review-summary">
            <div className="flex gap-2">
                <div className="shrink-0 pt-0.5">
                    <AiSparkleIcon />
                </div>
                <div className="min-w-0 flex-1 space-y-2">
                    {/* Title row + badge */}
                    <div className="flex items-center gap-2 flex-wrap">
                        <h3 className="sm:text-sm text-brand-black font-semibold">{title}</h3>
                        {badgeText && (
                            <Badge className="text-xs font-medium px-1.5 py-0.5 bg-brand-blue-100 text-brand-blue-700 border-brand-blue-200 hover:bg-brand-blue-100">
                                {badgeText}
                            </Badge>
                        )}
                    </div>
                    {/* Description aligned with title */}
                    <p className="sm:text-sm text-brand-gray-600 leading-relaxed">{description}</p>
                    {/* Star rating line aligned with title */}
                    <div className="flex items-center gap-1.5 sm:text-xs text-brand-gray-600">
                        <StarIcon
                            filled={true}
                            opacity={1}
                            className="size-4 text-rating shrink-0"
                            aria-hidden="true"
                        />
                        <span className="font-semibold text-brand-black">{formattedRating}</span>
                        <span>·</span>
                        <span>{t('product:rating.basedOnReviews', { count: reviewCount })}</span>
                    </div>
                </div>
            </div>
        </div>
    );
}
